[DRAFT] PPT export
sideqik/pdf-mage pull request #17
Opened 2021-05-28 16:08 UTC by dtpowl

2021-05-29 17:50 UTC, jeremyhaile requested changes

2021-05-29 17:50 UTC, jeremyhaile commented on lib/pdf_mage/workers/upload_pdf.rb
> +        validate_aws_config!
Couldn't we just call this at startup instead of every time a job runs?

2021-05-29 17:50 UTC, jeremyhaile commented on lib/pdf_mage/workers/upload_pptx.rb
> +        validate_aws_config!
Couldn't we just call this at startup instead of every time a job runs?

2021-05-29 17:50 UTC, jeremyhaile commented on lib/pdf_mage/workers/upload_pptx.rb
> +        obj.upload_file(pptx_filename(export_id))
I'm particularly confused about uploading here because of the file_uploader/upload_data! changes in the other PR. Sorry if I should remember how it works but could you remind what the flow is now?

2021-05-29 17:50 UTC, jeremyhaile commented on lib/pdf_mage/workers/upload_pptx.rb
> +        LOGGER.info "called bucket.object with argument #{export_id}"
Mean to leave both of these log statements?

2021-05-29 17:50 UTC, jeremyhaile commented on lib/pdf_mage/workers/upload_pptx.rb
> +    class UploadPptx < PdfMage::Workers::Base
Sort of weird to me that we have two different upload jobs vs one job with arguments.

2021-05-29 17:50 UTC, jeremyhaile commented on lib/pdf_mage/workers/upload_pptx.rb
> +    class UploadPptx < PdfMage::Workers::Base
Almost all of the code is copy/paste

2021-05-29 17:50 UTC, jeremyhaile commented on spec/unit/workers/upload_pdf_spec.rb
> +RSpec.describe PdfMage::Workers::UploadPdf do
Do we need a version of this for Pptx?

2021-05-29 17:50 UTC, jeremyhaile commented on lib/pdf_mage/workers/render_pptx.rb
> +        if CONFIG.aws_account_key
I guess it supports this but we always use S3. Should we remove this kind of confusing logic and just keep our main path?

2021-06-01 13:33 UTC, dtpowl commented on lib/pdf_mage/convert_api.rb
> +        'Secret' => 'jjlOQjqI7Nl2nY8d'#CONFIG['convertapi_secret']
fix this

2021-06-01 13:34 UTC, jeremyhaile commented on lib/pdf_mage/convert_api.rb
> +            #gsub(':secret', CONFIG['convertapi_secret']).
Comment?

2021-06-01 13:35 UTC, jeremyhaile commented on lib/pdf_mage/workers/upload_file.rb
> +        obj.upload_file(filename)
Need to specify content_disposition and content_type here. May want to specify content_length and content_md5 here. If upload_file doesn't support, may have to switch to put_object.

2021-06-01 13:36 UTC, jeremyhaile commented on spec/unit/workers/upload_pdf_spec.rb
> +      PdfMage::Workers::UploadPdf.perform_async(pdf_id, callback_url, meta)
Spec is broken since you renamed.

2021-06-01 13:36 UTC, jeremyhaile commented on spec/unit/workers/upload_pdf_spec.rb
> +# coding: utf-8
Spec name should be upload_file_spec.rb

2021-06-01 13:37 UTC, jeremyhaile commented on spec/unit/workers/upload_pdf_spec.rb
> +RSpec.describe PdfMage::Workers::UploadPdf do
Rename to UploadFile

2021-06-01 13:38 UTC, jeremyhaile commented on lib/pdf_mage/convert_api.rb
> +    url = CONVERT_PATTERN.
May not want to add a gem for this, but addressable has a nice template pattern for this: https://github.com/sporkmonger/addressable

2021-06-02 16:47 UTC, dtpowl commented on lib/pdf_mage/workers/upload_pdf.rb
> +        validate_aws_config!
Done

2021-06-02 16:47 UTC, dtpowl commented on lib/pdf_mage/workers/upload_pptx.rb
> +        validate_aws_config!
Done

2021-06-02 16:48 UTC, dtpowl commented on lib/pdf_mage/workers/render_pptx.rb
> +        if CONFIG.aws_account_key
Done

2021-06-02 16:53 UTC, dtpowl commented on lib/pdf_mage/convert_api.rb
> +    url = CONVERT_PATTERN.
I didn't know it did that! I don't know if it's worth adding a dependency just for this, but let's consider it again if we add a second usage of this pattern.

2021-06-03 23:39 UTC, dtpowl commented
Merging with verbal approval from @jeremyhaile

2021-06-03 23:40 UTC, merged